version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATABASE: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  redis:
    image: redis:latest
    restart: always
    volumes:
      - cache:/data
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379

  web:
    build: .
    command: /usr/src/app/run.sh
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles/
      - ./media:/usr/src/app/media/
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT}:8000
    env_file: .env
    environment:
      - DEBUG=false
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  celery:
    restart: always
    build: .
    command: celery -A config.celery.app worker -l info
    env_file: .env
    environment:
      - DEBUG=false
      - REDIS_URL=redis://redis:${REDIS_PORT}
    depends_on:
      - db
      - redis
      - web

volumes:
  db_data:
  cache:
