# Generated by Django 4.0.5 on 2022-06-17 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('column_separator', models.CharField(choices=[(',', 'comma (,)'), (';', 'semicolon (;)'), (':', 'colon (:)'), ('\t', 'tab ( )')], default=',', max_length=16)),
                ('string_character', models.CharField(choices=[('Double-quote (")', 'Double Quote'), ("Single-quote (')", 'Single Quote')], default="Single-quote (')", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'schema',
                'verbose_name_plural': 'schemas',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready')], default='Processing', max_length=16)),
                ('rows', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets_schema', to='fake_data.schema')),
            ],
            options={
                'verbose_name': 'dataSet',
                'verbose_name_plural': 'dataSet',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('Full name', 'Fullname'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domainname'), ('Company name', 'Companyname'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], default='Text', max_length=16)),
                ('filter', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='fake_data.schema')),
            ],
            options={
                'verbose_name': 'column',
                'verbose_name_plural': 'columns',
            },
        ),
    ]
